version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3-browsers-legacy
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build
          command: yarn build
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn test
      - store_test_results:
          path: test-results
      - run:
          name: Echo stuff
          command: |
            echo "Fork PR username: $CIRCLE_PR_USERNAME"
            echo "NPM auth token: $NPM_AUTH_TOKEN"
            echo "combined:
            echo [ "${CIRCLE_PR_USERNAME}" == "" ] && [ "${NPM_AUTH_TOKEN}" != "" ]
      - when:
            condition: false
            steps:
            - run:
                name: Publish Canary
                command: |
                    echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > .npmrc
                    npm run ci:release:canary
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
